### ISSUE TITLE
Adaptive alpha p-value in UVA

### ISSUE THREAD

**Issue by kjwalter89** [hfgolino/EGAnet#100]
I'm getting the following error message when I try to run UVA:

Error in redundancy.process(data = data, cormat = cormat, n = n, model = model,  : 
  "alpha" and "adapt" have been removed from UVA. Please use "threshold"

Is it no longer possible to use "adapt" at all?

**Comment by AlexChristensen** [comment]
At least in the updated package, this functionality has been removed in favor of `"threshold"` which is demonstrated to be more accurate than `"adapt"`. `"adapt"` tended to overestimate the number of locally dependent pairs.

If you're looking to be more lenient, you can try a threshold = 0.15 or 0.20

**Comment by AlexChristensen** [comment]
Linking archived {EGAnet} version 1.2.0 which has this capability still: https://cran.r-project.org/src/contrib/Archive/EGAnet/EGAnet_1.0.0.tar.gz
