### ISSUE TITLE
error itemStability.loadings function of itemStability

### ISSUE THREAD

**Issue by tlecerf1205** [hfgolino/EGAnet#104]
Computing results...
An error has occurred in the 'itemStability.loadings' function of 'itemStability':

Error in comm.str[names(minimum_value), as.character(i)] : 
  subscript out of bounds

R version (MAC) : R.app GUI 1.79 (8160 Big Sur ARM build)
EGA version : EGAnet_1.2.4         
NetworkToolbox_1.4.3

MAC OS ventura 13.0.1

thank you

**Comment by AlexChristensen** [comment]
Hi @tlecerf1205,

There have been a couple updates to the package recently that perhaps fix this issue.

Could you update from GitHub and let me know if this issue persists:

```
devtools::install_github("hfgolino/EGAnet")
```

If the issue persists, would you mind emailing me the dataset so I can verify where the bug is happening: alexpaulchristensen@gmail.com

**Comment by tlecerf1205** [comment]
Hi Hudson,
Still not working…

Here the error message; a little bit different.
---------------
Please open a new issue on GitHub (bug report): https://github.com/hfgolino/EGAnet/issues/new/choose

Be sure to provide the following information:

To Reproduce:
• Function error occurred in: itemStability.loadings function of itemStability

R and EGAnet versions:
• R version: 4.2.2
• EGAnet version: 1.2.4

Operating System:
• OS: MAC OS ventura
• Version: 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103
Error in order(names(stability.dimensions)) : argument 1 is not a vector

Thank you
Best
Thierry


De : Alexander Christensen ***@***.***>
Répondre à : hfgolino/EGAnet ***@***.***>
Date : jeudi, 17 novembre 2022 à 14:46
À : hfgolino/EGAnet ***@***.***>
Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of itemStability (Issue #104)


Hi @tlecerf1205<https://github.com/tlecerf1205>,

There have been a couple updates to the package recently that perhaps fix this issue.

Could you update from GitHub and let me know if this issue persists:

devtools::install_github("hfgolino/EGAnet")

If the issue persists, would you mind emailing me the dataset so I can verify where the bug is happening: ***@***.******@***.***>

**Comment by tlecerf1205** [comment]
Hi Alexander ? Hudson ?
Sorry for my mistake ; I thought it was Hudson who sent me the message.
You will find attached the data; it’s a correlation matrix with 15 variables of the French WISC-V.
I plan to submit a paper on the WISC-V for a special issue on the construct validity of the WISC.

Thank you for all

Best
Thierry

De : Alexander Christensen ***@***.***>
Répondre à : hfgolino/EGAnet ***@***.***>
Date : jeudi, 17 novembre 2022 à 19:31
À : hfgolino/EGAnet ***@***.***>
Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of itemStability (Issue #104)


Hi @tlecerf1205<https://github.com/tlecerf1205>,

Would you mind sending me your data file so I can try to see what's happening?

Please send email to ***@***.******@***.***>

**Comment by AlexChristensen** [comment]
Hi @tlecerf1205,

This is Alex. I was unable to receive your correlation matrix -- I believe that sending through email to GitHub does not work. I think you'll have to send to correlation matrix directly to me rather than in response to the GitHub email.

**Comment by hfgolino** [comment]
Have you installed the new version of the package available on GitHub?

**Comment by tlecerf1205** [comment]
Hi Alex,
For an unknown reason until now, I have installed the new version on my Macbook air (M1) and your package works.
But with IMac I have still the error message. Maybe the problem is with R and/or RStudio, NOT with your package.

By the way, that works on my Macbook…

Thank you for all.

Best,
Thierry

De : hfgolino ***@***.***>
Répondre à : hfgolino/EGAnet ***@***.***>
Date : jeudi, 24 novembre 2022 à 14:05
À : hfgolino/EGAnet ***@***.***>
Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of itemStability (Issue #104)

Have you installed the new version of the package available on GitHub?

**Comment by hfgolino** [comment]
Try updating R and RStudio on your iMac too.

Cheers,
Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qui., 24 de nov. de 2022 às 08:20, tlecerf1205 ***@***.***>
escreveu:

> Hi Alex,
> For an unknown reason until now, I have installed the new version on my
> Macbook air (M1) and your package works.
> But with IMac I have still the error message. Maybe the problem is with R
> and/or RStudio, NOT with your package.
>
> By the way, that works on my Macbook…
>
> Thank you for all.
>
> Best,
> Thierry
>
> De : hfgolino ***@***.***>
> Répondre à : hfgolino/EGAnet ***@***.***>
> Date : jeudi, 24 novembre 2022 à 14:05
> À : hfgolino/EGAnet ***@***.***>
> Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
> Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of
> itemStability (Issue #104)
>
> Have you installed the new version of the package available on GitHub?
>
> On Wed, Nov 23, 2022, 10:03 AM Alexander Christensen <

**Comment by tlecerf1205** [comment]
Hi Hudson,
I have reinstalled R and R Studio, but there is still “general” problem.
For instance, I can’t open files with the function “read.csv2”… it crashes.

Some problem with Xquartz?
Anyway, thank you

Cheers
Thierry

De : hfgolino ***@***.***>
Répondre à : hfgolino/EGAnet ***@***.***>
Date : samedi, 26 novembre 2022 à 15:07
À : hfgolino/EGAnet ***@***.***>
Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of itemStability (Issue #104)

Try updating R and RStudio on your iMac too.

Cheers,
Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qui., 24 de nov. de 2022 às 08:20, tlecerf1205 ***@***.***>
escreveu:

> Hi Alex,
> For an unknown reason until now, I have installed the new version on my
> Macbook air (M1) and your package works.
> But with IMac I have still the error message. Maybe the problem is with R
> and/or RStudio, NOT with your package.
>
> By the way, that works on my Macbook…
>
> Thank you for all.
>
> Best,
> Thierry
>
> De : hfgolino ***@***.***>
> Répondre à : hfgolino/EGAnet ***@***.***>
> Date : jeudi, 24 novembre 2022 à 14:05
> À : hfgolino/EGAnet ***@***.***>
> Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
> Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of
> itemStability (Issue #104)
>
> Have you installed the new version of the package available on GitHub?
>
> On Wed, Nov 23, 2022, 10:03 AM Alexander Christensen <

**Comment by hfgolino** [comment]
I have no idea! But that's an R/RStudio issue and your OS. Unfortunately,
we can't help.

Cheers,

Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em seg., 28 de nov. de 2022 às 02:48, tlecerf1205 ***@***.***>
escreveu:

> Hi Hudson,
> I have reinstalled R and R Studio, but there is still “general” problem.
> For instance, I can’t open files with the function “read.csv2”… it
> crashes.
>
> Some problem with Xquartz?
> Anyway, thank you
>
> Cheers
> Thierry
>
> De : hfgolino ***@***.***>
> Répondre à : hfgolino/EGAnet ***@***.***>
> Date : samedi, 26 novembre 2022 à 15:07
> À : hfgolino/EGAnet ***@***.***>
> Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
> Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of
> itemStability (Issue #104)
>
> Try updating R and RStudio on your iMac too.
>
> Cheers,
> Hudson
>
>
>
> *Hudson Golino*
> *Associate Professor*
> *Department of Psychology*
>
> *E* ***@***.*** ***@***.***>
>
> *University of Virginia*
>
> 1023 Millmont St, Office 115
> Charlottesville, VA 22903
>
>
>
>
> Em qui., 24 de nov. de 2022 às 08:20, tlecerf1205 ***@***.***>
> escreveu:
>
> > Hi Alex,
> > For an unknown reason until now, I have installed the new version on my
> > Macbook air (M1) and your package works.
> > But with IMac I have still the error message. Maybe the problem is with
> R
> > and/or RStudio, NOT with your package.
> >
> > By the way, that works on my Macbook…
> >
> > Thank you for all.
> >
> > Best,
> > Thierry
> >
> > De : hfgolino ***@***.***>
> > Répondre à : hfgolino/EGAnet ***@***.***>
> > Date : jeudi, 24 novembre 2022 à 14:05
> > À : hfgolino/EGAnet ***@***.***>
> > Cc : Thierry Lecerf ***@***.***>, Mention ***@***.***>
> > Objet : Re: [hfgolino/EGAnet] error itemStability.loadings function of
> > itemStability (Issue #104)
> >
> > Have you installed the new version of the package available on GitHub?
> >
> > On Wed, Nov 23, 2022, 10:03 AM Alexander Christensen <

**Comment by AlexChristensen** [comment]
See solution in #107

**Comment by tlecerf1205** [comment]
Hi Hudson,
I have one question regarding the walktrap community detection algorithm.
In your paper, you said that you choose four steps to detect the number of dimensions.
However, Pons and Latapy (2006) said that “… best results are obtained using length 3 ≤ t ≤ 8…. a good empirical compromise is to choose t = 4 or t = 5”.

So my question : Can it be possible that the number of dimensions can be slightly different with 4 or 5 steps?
Can I modify it in your function “cluster_walktrap” (steps = 5)?
I tried to modify it with “trace” (trace("cluster_walktrap", edit = TRUE)) but it doesn’t work!
Where is my mistake?
Thank you

Cheers
Thierry
