### ISSUE TITLE
Item stability possible bug

### ISSUE THREAD

**Issue by paperbag2449** [hfgolino/EGAnet#107]
Hi, Hudson and Alex! Happy Holidays! 

Item Stability Analysis

Organizing data...done

Computing results...
An error has occurred in the 'itemStability.loadings' function of 'itemStability':

Error in comm.str[names(minimum_value), as.character(i)] : 
  subscript out of bounds

Please open a new issue on GitHub (bug report): https://github.com/hfgolino/EGAnet/issues/new/choose

Be sure to provide the following information:

To Reproduce:
 • Function error occurred in: itemStability.loadings function of itemStability

R and EGAnet versions:
 • R version: 4.2.2
 • EGAnet version: 1.2.4

Operating System:
 • OS: Windows
 • Version: 10 x64 build 19044

Code that produced the error:

working2<-subset(working,select=-c(MMM19,MMM34,MMM20_35,MMM1,MMM3,MMM22,MMM2,
                                   MMM5,MMM31,MMM4))

boot.MMM <- bootEGA(data = working2, iter = 400, plot.type = "GGally",
                    EGA.type = "riEGA",
                    algorithm = "louvain",
                    consensus.method = "lowest_tefi",
                    type = "parametric", ncores = 2)

itemStability(boot.MMM)

I had run essentially the same code quite a few time just immediately with no problems

**Comment by paperbag2449** [comment]
Sorry, just seeing this was already reported. I did update with the latest GitHub version and still got the bug.

**Comment by AlexChristensen** [comment]
@paperbag2449 (Gary, right?),

I hope you've had a pleasant holiday.

Would you mind attaching the data that's having the issue either to this thread or via email to: alexpaulchristensen@gmail.com?

**Comment by paperbag2449** [comment]
Thanks, Alex, I have sent a link to your email. All the best, Gary

From: Alexander Christensen ***@***.***>
Sent: 26 December 2022 15:28
To: hfgolino/EGAnet ***@***.***>
Cc: Brown, Gary ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [hfgolino/EGAnet] Item stability possible bug (Issue #107)


@paperbag2449<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpaperbag2449&data=05%7C01%7Cgary.brown%40rhul.ac.uk%7C6ddb6ff89a6c47f0d44208dae755cbc2%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C638076652923720138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TbJH7neGNqAd6nuGeGCGkujiAK4YQp12PDsnwLzE4s0%3D&reserved=0> (Gary, right?),

I hope you've had a pleasant holiday.

Would you mind attaching the data that's having the issue either to this thread or via email to: ***@***.******@***.***>?

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhfgolino%2FEGAnet%2Fissues%2F107%23issuecomment-1365249980&data=05%7C01%7Cgary.brown%40rhul.ac.uk%7C6ddb6ff89a6c47f0d44208dae755cbc2%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C638076652923720138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1Ej4NHkJJNzfGE2sq7q0GUynNQ8wczdMHD4vUfRt6E%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARSWGNOUPI76Q5WOL5Y6G53WPG2QTANCNFSM6AAAAAATJWV4VU&data=05%7C01%7Cgary.brown%40rhul.ac.uk%7C6ddb6ff89a6c47f0d44208dae755cbc2%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C638076652923720138%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FXDgM1kqOaokyKJweb9uGOXr0UqwRUhsYUCvjCNaIyw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

This email, its contents and any attachments are intended solely for the addressee and may contain confidential information. In certain circumstances, it may also be subject to legal privilege. Any unauthorised use, disclosure, or copying is not permitted. If you have received this email in error, please notify us and immediately and permanently delete it. Any views or opinions expressed in personal emails are solely those of the author and do not necessarily represent those of Royal Holloway, University of London. It is your responsibility to ensure that this email and any attachments are virus free.

**Comment by AlexChristensen** [comment]
Thanks, Gary (@paperbag2449)!

The patch was just pushed to GitHub. `row.names` were not defined within `net.loads` for unidimensional structures.

Should be fixed now -- I got results with your data file without error.

Let me know either way

**Comment by paperbag2449** [comment]
Working perfectly, thanks!

From: Alexander Christensen ***@***.***>
Sent: 26 December 2022 16:09
To: hfgolino/EGAnet ***@***.***>
Cc: Brown, Gary ***@***.***>; Mention ***@***.***>
Subject: [EXT] Re: [hfgolino/EGAnet] Item stability possible bug (Issue #107)


Thanks, Gary ***@***.***<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpaperbag2449&data=05%7C01%7Cgary.brown%40rhul.ac.uk%7C0b07867b63234301a14908dae75b6f1a%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C638076677138074916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=70Ygp1bNi%2FVoT40hSbyaSx32Tkv5ztEDhh0j%2BskCKhY%3D&reserved=0>)!

The patch was just pushed to GitHub. row.names were not defined within net.loads for unidimensional structures.

Should be fixed now -- I got results with your data file without error.

Let me know either way

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fhfgolino%2FEGAnet%2Fissues%2F107%23issuecomment-1365267114&data=05%7C01%7Cgary.brown%40rhul.ac.uk%7C0b07867b63234301a14908dae75b6f1a%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C638076677138074916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Sk3MaK20xs2puRLkYgV%2BU%2F7YNogKMkcACWKrzFROqxI%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARSWGNIO65R4U57GAZ3VDDDWPG7H5ANCNFSM6AAAAAATJWV4VU&data=05%7C01%7Cgary.brown%40rhul.ac.uk%7C0b07867b63234301a14908dae75b6f1a%7C2efd699a19224e69b601108008d28a2e%7C0%7C0%7C638076677138074916%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ThPHtlFPfj5X2%2FEm2P18EpqGcRx6tCTP75DP5okFyvQ%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

This email, its contents and any attachments are intended solely for the addressee and may contain confidential information. In certain circumstances, it may also be subject to legal privilege. Any unauthorised use, disclosure, or copying is not permitted. If you have received this email in error, please notify us and immediately and permanently delete it. Any views or opinions expressed in personal emails are solely those of the author and do not necessarily represent those of Royal Holloway, University of London. It is your responsibility to ensure that this email and any attachments are virus free.

**Comment by AlexChristensen** [comment]
Awesome! Thanks, Gary!
