### ISSUE TITLE
Item stability following bootEGA using random intercept

### ISSUE THREAD

**Issue by paperbag2449** [hfgolino/EGAnet#113]
Please see attached output. Following bootEGA with riEGA, items 16,17,and 18 come out with 0 permutations in original community on the plot, although they are stable in another community in the raw output. I believe I have only encountered this with riEGA.  

[](url)
![Item stability](https://user-images.githubusercontent.com/73753397/227883431-fbbfc3be-14d7-41f0-bde8-868954398796.png)

**Comment by AlexChristensen** [comment]
See other issue: https://github.com/hfgolino/EGAnet/issues/113

Closing because it will be resolved in next branch merge from: https://github.com/hfgolino/EGAnet/tree/major-changes
