### ISSUE TITLE
Error in itemStability.loadings function of itemStability

### ISSUE THREAD

**Issue by paperbag2449** [hfgolino/EGAnet#115]
To Reproduce:
 • Function error occurred in: itemStability.loadings function of itemStability

R and EGAnet versions:
 • R version: 4.2.2
 • EGAnet version: 1.2.5.1

Operating System:
 • OS: Windows
 • Version: 10 x64 build 22621
Warning message:
In net.loads(A = graphs[[i]], wc = memberships[, i]) :
  The following nodes were found to have NA community membership: SABS3, SABS27, SABS46, SABS51, SABS53, SABS60 
 The nodes have been removed from the loadings matrix.

**Comment by paperbag2449** [comment]
Now seems to be fixed, thanks!

**Comment by paperbag2449** [comment]
Sorry, spoke too soon. It worked three times then the bug re-emerged. No pattern to when it happens that I can detect.

**Comment by 000Annemarie** [comment]
I am experiencing the same problem:
To Reproduce:
• Function error occurred in: itemStability.loadings function of itemStability

R and EGAnet versions:
• R version: 4.3.0
• EGAnet version: 1.2.5.1

Operating System:
• OS: Windows
• Version: 10 x64 build 22621

@paperbag2449: Have you found a solution yet?

**Comment by paperbag2449** [comment]
I haven't tried in a few weeks, but the problem was still around last I tried. I know the team is working generally on the net loadings functions.

**Comment by hfgolino** [comment]
Hi All,

We are working on the issue.

Right now, we recommend you install the newest version of the package from
Github, and contact me via email at ***@***.*** if the issue
persists.

Cheers,
Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qui., 8 de jun. de 2023 às 08:55, paperbag2449 ***@***.***>
escreveu:

**Comment by paperbag2449** [comment]
Thanks, Hudson. This particular problem I think only appears in the Github version (1.2.5.1) and not in the current CRAN version (1.2.3)

**Comment by 000Annemarie** [comment]
Hello @paperbag2449, You are right! I removed the 1.2.5.1 version and installed version 1.2.3, and now everything is running smoothly. Thank you for sharing this helpful tip!

Annemarie

**Comment by AlexChristensen** [comment]
We will be removing average item loadings in `itemStability` in future versions to avoid unnecessary errors between `itemStability` and `net.loads`
