### ISSUE TITLE
EGAnet and bootEGA not plotting median graph

### ISSUE THREAD

**Issue by Andka415** [hfgolino/EGAnet#119]
Hi,
I am trying to use EGA and bootEGA to explore the structure of a psychological network. 
The network concists of 18 different mean scores, from 18 different questionnaires. 
I am also using non-parametric resampling, since my data is skewed. 

However, the plot I am getting is not the median plot. For example I get a median freq of 4, but the plot is constantly giving me a 5 dim plot, even when I am changing the seed before I plot or the argument "consensus.method". I have also tried different agorithms, walktrap and spinglass.

**Comment by AlexChristensen** [comment]
HI @Andka415,

The median plot is not based on the median number of communities detected but rather the median network structure with the community detection algorithm applied to it.

The median network structure is the median value of each node-to-node edge across the bootstraps. This structure reflects the expected value of the each edge across sampling variance (based on the bootstrap). This median network structure then has the community detection algorithm applied to it.

This application can result in the number of communities in the median network structure than the median number of communities detected in the bootstrap.

Could you supply the `$frequency` and `$summary.table` output in this thread?

**Comment by Andka415** [comment]
# of Factors Frequency
[1,]            3     0.028
[2,]            4     0.892
[3,]            5     0.080

**Comment by AlexChristensen** [comment]
Thank you, could you also supply your {EGAnet} version? (use `packageVersion("EGAnet")`)

I'm not certain that this finding is an issue, per se, but we're working on updating everything internally and I'd like to sticky this issue in case it is an issue rather than a methodological nuance.

**Comment by Andka415** [comment]
Hi Alex,
Here is the version of EGAnet:
‘1.2.5.1’

**Comment by AlexChristensen** [comment]
Possibly an issue but should be fixed in a future merge: https://github.com/hfgolino/EGAnet/tree/major-changes

It's possible that the median graph will not match the empirical `EGA` graph

Closing as the coding issue should be resolved
