### ISSUE TITLE
add user-defined `wc` to `itemStability` and `dimensionStability`

### ISSUE THREAD

**Issue by AlexChristensen** [hfgolino/EGAnet#121]
what the title says

**Comment by paperbag2449** [comment]
It's like you can read my mind....

**Comment by hfgolino** [comment]
That's an innovation we're implementing in the package, Gary: mind reading!
hahaha



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em dom., 18 de jun. de 2023 às 18:52, paperbag2449 ***@***.***>
escreveu:

**Comment by paperbag2449** [comment]
Excellent idea! You can name the new field "psycholexics"!

**Comment by hfgolino** [comment]
Hahha

**Comment by AlexChristensen** [comment]
Seems like this capability might already be present in version 1.2.5.1; however, it's definitely present in https://github.com/hfgolino/EGAnet/tree/major-changes

Here's an example:

```
# Load package
library(EGAnet)

# Bootstrap EGA
boot <- bootEGA(
  data = wmt2[,7:24],
  type = "parametric", iter = 500,
  plot.typicalStructure = FALSE
)

# Item Stability
itemStability(
  boot, IS.plot = TRUE,
  structure = c( # this structure is nonsense (merely for example)
    rep(1, 5), rep(2, 5),
    rep(3, 5), rep(4, 2),
    5
  )
)
```

With output:

```
> # Bootstrap EGA
> boot <- bootEGA(
+   data = wmt2[,7:24],
+   type = "parametric", iter = 500,
+   plot.typicalStructure = FALSE
+ )
/ [====================] 100% elapsed: 18s ~remaining:  0s
> # Item Stability
> itemStability(
+   boot, IS.plot = TRUE,
+   structure = c(
+     rep(1, 5), rep(2, 5),
+     rep(3, 5), rep(4, 2),
+     5
+   )
+ )
EGA Type: EGA 
Bootstrap Samples: 500 (Parametric)

Proportion Replicated in Empirical Dimensions:

 wmt1  wmt2  wmt3  wmt4  wmt5  wmt6  wmt7  wmt8  wmt9 wmt10 
1.000 1.000 1.000 0.896 0.974 0.650 0.514 0.484 0.426 0.644 
wmt11 wmt12 wmt13 wmt14 wmt15 wmt16 wmt17 wmt18 
0.414 0.566 0.548 0.588 0.614 0.026 0.034 0.000 
```

Note that, for effect, singleton communities (`wmt18`) work (#99)

Closing with future merge from: https://github.com/hfgolino/EGAnet/tree/major-changes
