### ISSUE TITLE
Question: Is wTO + addaptive alpha still the best way to handle local dependency between items?

### ISSUE THREAD

**Issue by E-Mendez** [hfgolino/EGAnet#122]
Hi!

I found out I cannot apply the routine proposed in Christensen et al (2020), which is UVA with wTO + Adaptive alpha (1-). Said change was applied in version  1.2.0, to remove dependencies (2-).

_( Error in redundancy.process(data = data, cormat = cormat, n = n, model = model, :
"alpha" and "adapt" have been removed from UVA. Please use "threshold" )_

My questions are: 
1) Is the routine proposed in (1-) still the preferred method? Or I'm behind in the literature?
2) And... is the removal of those options only a computational decision regarding dependency hells aimed at a cleaner code, or again it is based also on theoretical decisions preferring the mode "threshold"?

Thank you for your work!!

### Sources

1- Christensen, A. P., Garrido, L. E., & Golino, H. (2020). Unique variable analysis: A novel approach for detecting redundant variables in multivariate data. PsyArXiv, 10.

2- [REMOVE: "alpha" and "adapt" options in `UVA` (removes {fitdistrplus} dependency)](https://github.com/hfgolino/EGAnet/blob/master/NEWS)

**Comment by AlexChristensen** [comment]
Hi @E-Mendez,

Based on simulation work, adaptive alpha is not the best way to handle local dependencies.

The main manuscript for `UVA` was just published at _Multivariate Behavioral Research_: https://www.tandfonline.com/doi/abs/10.1080/00273171.2023.2194606

Attaching preprint for direct access: [Unique Variable Analysis_preprint.pdf](https://github.com/hfgolino/EGAnet/files/11850996/Unique.Variable.Analysis_preprint.pdf)

**Comment by AlexChristensen** [comment]
See commit referencing this issue

Support for `auto = FALSE`, `type = "alpha"` (adaptive alpha), and `type = "alpha"` will no longer be provided (bugs will not be fixed)

The goal is to move toward best practices that are published in MBR (see citation in thread)

Closing with commit
