### ISSUE TITLE
[CRAN] Install problem

### ISSUE THREAD

**Issue by skybluesky94** [hfgolino/EGAnet#141]
**Hello. 

I tried to install EGAnet packages in R program, but it doesn't work.

this is what i experienced.**

> install.packages("EGAnet")
‘C:/Users/skybl/AppData/Local/R/win-library/4.3’의 위치에 패키지(들)을 설치합니다.
(왜냐하면 ‘lib’가 지정되지 않았기 때문입니다)
Warning in install.packages :
  package ‘EGAnet’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages

**and i also tried another version of installing.**

> if(!"devtools" %in% row.names(installed.packages())){
+   install.packages("devtools")
+ }
> 
> devtools::install_github("hfgolino/EGAnet")
Downloading GitHub repo hfgolino/EGAnet@HEAD
Skipping 1 packages not available: BGGM
── R CMD build ─────────────────────────────────────────────────────
✔  checking for file 'C:\Users\skybl\AppData\Local\Temp\Rtmpcj6jxC\remotes13801e7e1079\hfgolino-EGAnet-65c71fb/DESCRIPTION' (638ms)
─  preparing 'EGAnet': (4.5s)
✔  checking DESCRIPTION meta-information ... 
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (1.1s)
─  checking for empty or unneeded directories
─  building 'EGAnet_2.0.2.tar.gz'
   
‘C:/Users/skybl/AppData/Local/R/win-library/4.3’의 위치에 패키지(들)을 설치합니다.
(왜냐하면 ‘lib’가 지정되지 않았기 때문입니다)
ERROR: dependency 'BGGM' is not available for package 'EGAnet'
* removing 'C:/Users/skybl/AppData/Local/R/win-library/4.3/EGAnet'
Warning message:
In i.p(...) :
  패키지 ‘C:/Users/skybl/AppData/Local/Temp/Rtmpcj6jxC/file13803d264bf0/EGAnet_2.0.2.tar.gz’의 설치가 0이 아닌 종료상태를 가졌습니다.

**Because R said the version is not suitable for EGAnet packages, i changed R version 2023 to 2022. But it still doesn't work. So i wonder how can I install this package in my R studio. 
Thanks.**

**Comment by AlexChristensen** [comment]
Hi @skybluesky94,

Unfortunately, one of the dependencies for {EGAnet} was archived on CRAN, it archived all other packages that depended on it. So, although the source dependency was updated to CRAN, all other packages remain archived until they are updated. So, until {BGGM} can be updated on CRAN, {EGAnet} will remain archived.

In the meantime, you can still install {EGAnet} using GitHub:

```
# First, install {BGGM}
devtools::install_github("cran/BGGM")

# Second, install {EGAnet}
devtools::install("hfgolino/EGAnet")
```

Leaving this issue open until the archival dependency chain on CRAN is resolved

**Comment by skybluesky94** [comment]
It works. Thank you!
