### ISSUE TITLE
BGGM package was removed from CRAN

### ISSUE THREAD

**Issue by mrsrome20** [hfgolino/EGAnet#143]
I tried to install the EGAnet package but R warned me that the BGGM package had been removed from CRAN. I install the latest available version of this package, but I have the doubt if this package have a problem

**Comment by AlexChristensen** [comment]
Thanks for creating this issue, @mrsrome20. We are actively working on resolving the issue

**Comment by AlexChristensen** [comment]
@mrsrome20, an updated version of {EGAnet} is back on CRAN for easier install

Closing as resolved

**Comment by mrsrome20** [comment]
Thank u so much

**Comment by mrsrome20** [comment]
Thank u so much, now it is working properly
