### ISSUE TITLE
edge.alpha argument not working in EGA plots

### ISSUE THREAD

**Issue by gonzalofranetovic** [hfgolino/EGAnet#144]
Hello, 

Just passing by to comment that the EGA plot argument "edge.alpha" is not working. I tried with 0 and 1 values and the result is the same.
Hope you can fix it.

Thanks and cheers!

**Comment by AlexChristensen** [comment]
Hi @gonzalofranetovic,

We appreciate the report. Can you provide a reproducible example?

I see:

```
plot(ega.wmt, edge.alpha = 0) 
```

![image](https://github.com/hfgolino/EGAnet/assets/32655669/3370d554-dad4-42c2-89f7-6988faee1668)

```
plot(ega.wmt, edge.alpha = 0.25) 
```

![image](https://github.com/hfgolino/EGAnet/assets/32655669/0e6efcc3-4ba9-4b54-94bb-6a7145350e2c)

```
plot(ega.wmt, edge.alpha = 0.50) 
```

![image](https://github.com/hfgolino/EGAnet/assets/32655669/44763ba9-4b36-4eea-8e89-41068fcc876c)

```
plot(ega.wmt, edge.alpha = 1)
````

![image](https://github.com/hfgolino/EGAnet/assets/32655669/547cd32e-bef2-4384-a622-dfb3c9cb9696)

On my end, `edge.alpha` appears to work as intended

**Comment by gonzalofranetovic** [comment]
Thank you very much for your quick and efficient response @AlexChristensen!
It was indeed a version problem. I updated it and that problem was corrected. But two more problems appeared :(
Now: 
1. edge.color in compare.EGA.plots only changes me the color of the links of the first graphic, leaving the rest with the colors that come by default (green and red).
2. legend.position = "none" does not work. The legend is still displayed.
I remain attentive and thank you very much!

`
# Obtain WMT-2 data
wmt <- wmt2[,7:24]

# Draw random samples of 300 cases
sample1 <- wmt[sample(1:nrow(wmt), 300),]
sample2 <- wmt[sample(1:nrow(wmt), 300),]

# Estimate EGAs
ega1 <- EGA(sample1)
ega2 <- EGA(sample2)

# Compare EGAs via plot
compare.EGA.plots(
  ega1, ega2,
  base = 1, # use "ega1" as base for comparison
  labels = c("Sample 1", "Sample 2"),
  rows = 1, columns = 2,
  edge.alpha = 0.5,
  edge.color = c("royalblue", "tomato"),
  legend.position = "none"
)
`

![image](https://github.com/hfgolino/EGAnet/assets/44820479/855acddf-d19b-48ee-a22b-28046a99be70)


I remain attentive and thank you very much!
