### ISSUE TITLE
dimensionality decision with bootEGA

### ISSUE THREAD

**Issue by mrsrome20** [hfgolino/EGAnet#147]
I am employing bootEGA to determine dimensionality, and I've observed a discrepancy in the decision when utilizing raw data compared to the polychoric matrix. The items under consideration are ordinal, featuring 4 or 5 categories each. The raw data bootEGA unequivocally indicates the presence of 4 dimensions, whereas the polychoric matrix bootEGA suggests 3 dimensions.

This inconsistency arises exclusively when employing the "glasso" method, as both decisions align when using the "tmfg" approach. Upon scrutinizing my data, I noted a lack of multivariate normality, which leads me to speculate whether this non-normality is a key factor influencing the discrepancy. Consequently, should I prioritize the "tmfg" method for its robustness in handling non-normally distributed data?

Thank you very much for dedicating your time to assist me in this matter. Your guidance is highly appreciated.

**Comment by hfgolino** [comment]
Hi.

Use the total entropy fit index to decide which dimensionality structure
fits the data better: the 3 or the 4-dimension solution.

Cheers,
Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em seg., 18 de dez. de 2023 às 15:25, mrsrome20 ***@***.***>
escreveu:
