### ISSUE TITLE
Compatibility with igraph 2.0.0

### ISSUE THREAD

**Issue by krlmlr** [hfgolino/EGAnet#148]
@AlexChristensen @hfgolino: This package fails its checks for the release candidate for igraph 2.0.0. See <https://github.com/igraph/rigraph/blob/main/revdep/problems.md> for details.

Is this a problem in your package? Should we be doing things differently?

Install the 2.0.0 release candidate using `pak::pak("igraph/rigraph")` .

We're planning to release igraph 2.0.0 in mid-January. Thank you for your help!

Tracker: https://github.com/igraph/rigraph/issues/989.

**Comment by AlexChristensen** [comment]
@krlmlr, confirmed that issue was on our end

Ran checks with the {igraph} 2.0.0 release candidate and did not identify any other issues -- you should be good to go

I'll leave this issue open until there is confirmation on your end

Thanks!

**Comment by krlmlr** [comment]
Thanks. From a very coarse look, it seems like the most recent change fixes the symptoms but also loses functionality. What was the purpose of the extra arguments to `EGA.estimate()` that were stored in `ellipse` ? If this is truly intended, is it really necessary to update the `ellipse` variable in https://github.com/hfgolino/EGAnet/commit/3f276b2d2005a1a8782845ac5d7cfde31dcffd9d?diff=split&w=1#diff-a57242e662fa0e51754e8df3591f3490e5e8d3a3e34bf2a1fc9e7466b4d170ffR664 ?

Either way, I'd appreciate if you could send an update to CRAN when it reopens.

**Comment by AlexChristensen** [comment]
Thanks for the quick look -- you're correct that the previous remedy lost some functionality. Just implemented a proper fix that maintains functionality

We will plan for an update to CRAN next week

**Comment by hfgolino** [comment]
Thanks for your message, Kirill.

We'll make all changes as you suggested, and submit a new version of the
package to CRAN ASAP.
Cheers,
Hudson



*Hudson Golino*
*Associate Professor*
*Department of Psychology*

*E* ***@***.*** ***@***.***>

*University of Virginia*

1023 Millmont St, Office 115
Charlottesville, VA 22903




Em seg., 1 de jan. de 2024 às 10:07, Alexander Christensen <
***@***.***> escreveu:

**Comment by krlmlr** [comment]
We're planning to send igraph to CRAN on January 23.

**Comment by hfgolino** [comment]
Awesome, thanks for the heads up!

**Comment by AlexChristensen** [comment]
Closing as {igraph} has been updated and no dependency issues remain: https://cran.r-project.org/package=igraph
