### ISSUE TITLE
Please do not change future options

### ISSUE THREAD

**Issue by HenrikBengtsson** [hfgolino/EGAnet#156]
Hello. Please do _not_ set future options from within your package, as in:

https://github.com/cran/EGAnet/blob/08fcbe48f56628d2d146d9d9f8d47e4cb09aaf12/R/helpers.R#L594

This might have unintended side effects for other packages and risk producing incorrect results elsewhere. R options are meant for end-users, not developers. If you need to tweak the settings, please do so temporarily, as explained in https://future.futureverse.org/articles/future-7-for-package-developers.html#avoid-changing-the-future-options.

**Comment by AlexChristensen** [comment]
Hi @HenrikBengtsson,

Thanks for pointing this conflict out to us. I have added a commit to the master branch that should resolve this conflict.

I am going to leave this issue open until we submit a new version to CRAN after which I will close as resolved.

**Comment by AlexChristensen** [comment]
Closing as updated version with this patch has been uploaded to CRAN: https://cran.r-project.org/web/packages/EGAnet/index.html
