### ISSUE TITLE
legend.names parameter in plot function no longer works

### ISSUE THREAD

**Issue by bbergsneider** [hfgolino/EGAnet#162]
Thank you for this fantastic package. I am recently experiencing a bug in which when I plot an EGAnet object, the legend.names parameter no longer works and does not allow me to define custom legend names (as described in this tutorial: https://r-ega.net/articles/plotting.html#change-names).

Is this a bug? Is there another way to define legend names?

Thank you!

**Comment by hfgolino** [comment]
Hi Brandon. What version of the package are you using? Can you share the
code you used? Hudson

**Comment by bbergsneider** [comment]
I'm using version 2.0.8. Here is my code:

```
df <- read.csv("severity_data.csv", stringsAsFactors = FALSE) %>% select(-Study,-ptid)
cor_matrix <- cor_auto(df, detectOrdinal = FALSE, npn.SKEPTIC = TRUE, forcePD = TRUE)
ega <- EGA(cor_matrix, n = nrow(df), plot.EGA = FALSE)
plot(ega, plot.args = list(node.size = 8, label.size = 3.5, color.palette = c("#387db8", "#e4211c", "#4caf4a"), legend.names=c("Dimension 1", "Dimension 2", "Dimension 3")))
```

Thanks!

**Comment by AlexChristensen** [comment]
Hi @bbergsneider ,

We've dropped the `plot.args`, so you can directly drop arguments into the `plot` function.

I believe that should work

**Comment by AlexChristensen** [comment]
Closing with an example

```
# Load {EGAnet}
library(EGAnet)

# Get EGA output
ega_output <- EGA(wmt2[,7:24], plot.EGA = FALSE)

# Plot
plot(
  ega_output, 
  node.size = 8, label.size = 3.5, 
  color.palette = c("#387db8", "#e4211c"), 
  legend.names = c("Dimension 1", "Dimension 2")
)
```

**Comment by bbergsneider** [comment]
Thank you! That fixed it
