### ISSUE TITLE
'S' is not positive definite

### ISSUE THREAD

**Issue by dynamic-biogeography** [hfgolino/EGAnet#19]
Hello,
I'm recurrently receiving the ''Error in EBICglasso.qgraph(S = data, n = n, lambda.min.ratio = 0.1, returnAllResults = FALSE,  :    'S' is not positive definite" error message. 
This occurs for distinct correlation matrices. 
I' wonder if there is a way to get around this?
Many thanks in advance.
Cheers
Cesar

**Comment by hfgolino** [comment]
Hi Cesar, yes.

You can find the nearest PD matrix using the nearPD function from the
Matrix package.

Could you, please, send me the full code you are using to hfg9s@virginia.edu
?

Cheers





*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em ter, 23 de abr de 2019 às 01:30, dynamic-biogeography <
notifications@github.com> escreveu:

**Comment by dynamic-biogeography** [comment]
Many thanks. Will look at that possibility.
Sended the files as asked.
Regards
Cesar
