### ISSUE TITLE
EGA with correlation matrix fails

### ISSUE THREAD

**Issue by DominiqueMakowski** [hfgolino/EGAnet#20]
Hey @hfgolino, thanks for the package.

It seems that EGA won't accept a correlation matrix as input. Am I missing something?

``` r
EGAnet::EGA(cor(mtcars), n = nrow(mtcars))
#> Error in EGAnet::EGA(cor(mtcars), n = nrow(mtcars)): object 'n.dim.sim' not found
```

<sup>Created on 2019-06-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hfgolino** [comment]
Hi Dominique, this is a bug I'll solve in the next few days. I'll update
the package on GitHub soon.

Could you, please, contact me again in one or two weeks to confirm if the
package is updated?
Best,

Hudson



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qua, 19 de jun de 2019 às 17:07, Dominique Makowski <
notifications@github.com> escreveu:

**Comment by DominiqueMakowski** [comment]
@hfgolino Sure, thanks ;)

**Comment by hfgolino** [comment]
EGA is working well with correlation matrices.

**Comment by Psych-MaXu** [comment]
Hey @hfgolino, thanks for the package.
I still have this bug. i first used the bootnet package, and run this script "Net1 <- estimateNetwork(data = data4[,4:25],default = 'IsingFit')". Then I take the matrix to a new variable, the script is that "matrix1 <- Net1$results$weiadj". Finally, i found this script "EGAnet::EGA(matrix1, n = 3934)" did not work.
is there something worng?

**Comment by AlexChristensen** [comment]
Hi @Psych-MaXu,

Please create a new issue as this usage is a separate issue from the original.

Please see: https://r-ega.net/articles/modular-approach.html

Also, please read the documentation as it does not say that a network can be input into `EGA`, so the function is working as expected: https://r-ega.net/reference/EGA.html

Finally, it is not recommended to using an Ising model network with community detection algorithms. The log of the odds-ratio weights are not suitable for community detection algorithms.
