### ISSUE TITLE
BootEGA

### ISSUE THREAD

**Issue by FranJuradog** [hfgolino/EGAnet#21]
Dear Hudson Golino,

I installed version 0.5 of the EGAnet package, with the intention of estimate the number of dimensions of a psychological test.  I have been able to perform all the steps of the exploratory and confirmatory analysis. However, When I use the "bootEGA" function, the following message appears,"the package called EGA is needed" and it does not run.

The error that returns is the following:
    Error in e$fun (obj, substitute(ex), parent.frame(), e$data) :
      worker initialization failed: there is no package called 'EGA'

We have reviewed the code to make sure we do not make any mistakes. Another colleagues have tried to execute the function and return the same error

Could you tell us any guide to solve this problem?

I am using the RStudio version 3. 6. 0.

Thank you in advance

**Comment by hfgolino** [comment]
Dear Fran,

I'm cc this email to Alex Christensen, that is helping me with the bootEGA
function. We should debug this problem soon.

Thanks,

Hudson



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em sáb, 29 de jun de 2019 às 15:44, FranJuradog <notifications@github.com>
escreveu:

**Comment by AlexChristensen** [comment]
Hi @FranJuradog,

This issue should be taken care of now -- please try re-installing package using the code:

`devtools::install_github("AlexChristensen/EGAnet")`

--or--

by installing the attached .tar.gz:

[EGAnet_0.6.0.tar.gz](https://github.com/hfgolino/EGAnet/files/3350543/EGAnet_0.6.0.tar.gz)

**Comment by hfgolino** [comment]
Bugs fixed.
