### ISSUE TITLE
Confusion about correlations

### ISSUE THREAD

**Issue by Mosen111** [hfgolino/EGAnet#34]
Dear Dr. Golino,
I wanted to check my understanding and make sure I am clear on the way EGA works.

1- Glasso is based on partial correlation and tmfg is based on zero-order correlations. is this correct? 

2- When inputting raw data in form of a data frame:  GLASSO automatically produces a partial correlation matrix from raw data, and EGAtmfg automatically produces a zero-order correlation matrix from raw data. Is this correct?

2- When inputting a zero-order correlations matrix, does GLASSO calculate a partial correlation matrix and EGAtmfg just use the zero-order correlation matrix as it is? 

3- We never need to input a partial correlation matrix to glasso, becuase it automatically produces it. is this right?

many thanks in advance,
Best,
Mosen.

**Comment by hfgolino** [comment]
You're right!

You can use both the raw data or a zero-order correlation, and it will automatically compute the regularized partial correlations for you if you're using glasso (in this case, the EGAnet package uses the EBICglasso function from qgraph). If you're using TMFG, then the resulting network will be built using zero-order correlations. However, there is a way to transform the TMFG network into a partial-correlations network. Check the manual of the NetworkToolbox package. Cheers, Hudson.

**Comment by Mosen111** [comment]
thanks a lot for the clarification
