### ISSUE TITLE
tefi() function throws NAs

### ISSUE THREAD

**Issue by OscarLecuona** [hfgolino/EGAnet#36]
Testing some EGA models on some questionnaire data (csv available at https://osf.io/m64wp/). Calculating model fit the entropy functions work normally except tefi(), which always throws NAs in all cases, even when increasing walktrap steps to 8. CRAN example works fine, also tried to re-install the package. Any clues on what could be happening? 

Thanks a lot, love the package <3

Typical output of tefi() on my data:

Variables detected as ordinal: I1; I2; I3; I4; I5; I6; I7; I8; I9; I10; I11; I12; I13; I14; I15; I16; I17; I18; I19; I20; I21; I22; I23; I24; I25; I26; I27; I28; I29; I30; I31; I32; I33; I34; I35; I36; I37; I38; I39
Variables detected as ordinal: I1; I4; I6; I9; I11; I15; I19; I20; I21; I24; I26; I29; I31; I33; I36
Variables detected as ordinal: I2; I7; I12; I16; I22; I27; I32; I37
Variables detected as ordinal: I3; I10; I14; I17; I25; I30; I35; I39
Variables detected as ordinal: I5; I8; I13; I18; I23; I28; I34; I38
  VN.Entropy.Fit Total.Correlation Average.Entropy
1            NaN               NaN             NaN
Warning message:
In log(cor1) : NaNs produced

**Comment by hfgolino** [comment]
Hi Oscar, calculate the correlation matrix, and then use the absolute values of the corr matrix as input to the tefi function. Cheers
