### ISSUE TITLE
centrality indices in EGAnet

### ISSUE THREAD

**Issue by izan-b** [hfgolino/EGAnet#39]
Hi
I have some problems with your package. please let me know what is the problem, if possible.
1- I can not find any function in EGAnet for centrality indices (betweenness, closeness and strength). any help

2-I am analyzing my data with "EGAnet" package, but the bellow error is emerged. the correlation matrix is problematic, but an related error emerged. any help.

Error in names(wc.sim$membership) <- colnames(data.sim) :
  'names' attribute [24] must be the same length as the vector [23]
In addition: Warning messages:
1: In vattrs[[name]][index] <- value :
  number of items to replace is not a multiple of replacement length

**Comment by AlexChristensen** [comment]
Hi @izan-b,

1. The EGAnet package does not have functions to directly compute centrality indices. Other R packages such as igraph, qgraph, and NetworkToolbox can be used to compute centrality measures.

- igraph: you will need to convert the network matrix into igraph's format using: `NetworkToolbox::convert2igraph(your_network)`

- qgraph: you will need to convert the network matrix into qgraph's format using: `qgraph_network <- qgraph(your_network)`

- NetworkToolbox: centrality measures can be computed directly on the network matrix. For example: `betweenness(your_network)`

2. Is it possible to provide more information on where this error is coming from? Specifically:

a. What version of EGAnet are you using?

b. What function did this error occur in?

c. Could you provide a replicable toy data example of this error?

**Comment by hfgolino** [comment]
Hi, @izan-b.

It seems that the problem lies in the estimation of the number of communities (Walktrap algorithm).

We can help, but you'll need to send us the info. Alex pointed above, ok?

Cheers,

Hudson

**Comment by izan-b** [comment]
Hi

Run attached file by my syntax and see what is the results

**Comment by izan-b** [comment]
Hi Alexander
Hear is the version of EGAnet i am using:
1)
Registered S3 methods overwritten by 'huge':
  method    from
  plot.sim  BDgraph
  print.sim BDgraph
Package: EGAnet: Exploratory Graph Analysis - A Framework for Estimating the
Number of Dimensions in Multivariate Data Using Network
Psychometrics
Version: 0.8
Created on: 2019-09-24

2) the function that emerge the error is
EGA

3) attached

Best regrads

**Comment by AlexChristensen** [comment]
Okay. I'm not sure that updating the package will help; however, I'll have you first try that using the following code:

`devtools::install_github("hfgolino/EGAnet")`

If you do not have the _devtools_ package installed, then you will have to install it first.

The data did not appear to attach -- could you try reattaching?

**Comment by izan-b** [comment]
Thanks
Attached is my data in spss format and my syntax.
Best regards
