### ISSUE TITLE
itemStability error

### ISSUE THREAD

**Issue by BernardoMoura** [hfgolino/EGAnet#52]
Hello,

I am having when using the itemStability function:
itemStability(bootEGAobject, orig.wc = EGA$wc)

The error is:
Error in sign.mat[j, ] : subscript out of bounds

I tried to investigate this better on my own and used options(error=recover) to spot the error. Apparently it is here:  for (m in 1:n) {
    item.id.samps[[m]] <- net.loads(bootega.obj$bootGraphs[[m]], 
      final.mat[, m])$std

May I add that I am using a 43 node network with n=1007. bootEGA() and EGA() run without problems. Only here it crashes.

Any input would be really helpful!
Thank you

**Comment by hfgolino** [comment]
Hi Bernardo, thanks for reaching out to us. Please, re-install the EGAnet package from GitHub (we updated the package today), and run the code below. Let me know if it works. After that, please run your own analysis again and check if the error persists. Thanks, Hudson.

wmt <- wmt2[,7:24]
ega.wmt <- EGA(data = wmt, model = "glasso")
boot.wmt <- bootEGA(data = wmt, n = 100, typicalStructure = TRUE,
                    plot.typicalStructure = TRUE, model = "glasso",
                    type = "parametric", ncores = 4)
itemStability(boot.wmt, orig.wc = ega.wmt$wc)

**Comment by BernardoMoura** [comment]
Hi Hudson, 
thank you for your answer.
I updated the package from GitHub. The code you've sent me worked perfectly. However, with my data it keeps returning the same "out of bounds" error and highlighting the same debug location that I've mentioned previously.

**Comment by hfgolino** [comment]
Hi Bernardo, is there any missing data in your dataset? If not, would you share the data with me, so I can try to run the bootEGA function and see if I can solve the problem (send it to hfg9s at Virginia.edu). Cheers

**Comment by hfgolino** [comment]
Solution: update EGAnet and networkToolbox.
