### ISSUE TITLE
bug in itemStability when orig.wc is a character vector

### ISSUE THREAD

**Issue by winsonfzyang** [hfgolino/EGAnet#65]
When i tried using named character vector for ega$wc as input for orig.wc in itemStability, the code doesn't work. It seems like it's not converting to numeric vector properly in lines 26-32

```
if (is.character(orig.wc)) {
    uni <- unique(orig.wc)
    num.comm <- orig.wc
    for (i in 1:length(uni)) {
      num.comm[which(num.comm == uniq[i])] <- i
    }
  }
```

Seems like a typo, and num.comm returns character vectors of numbers instead of integers.  Might this solve the bug?

```
if (is.character(orig.wc)) {
    uni <- unique(orig.wc)
    num.comm <- orig.wc
    for (i in 1:length(uni)) {
      num.comm[which(num.comm == uni[i])] <- i # Typo resolves here
    }
    num.comm <- as.integer(num.comm) # converts the character into integer
    names(num.comm) <- names(orig.wc) # puts the names back into num.comm
  }
```

**Comment by hfgolino** [comment]
Hi @winsonfzyang, thanks for pointing out this issue. It's corrected now (just update the package via GitHub). Please, let us know if you find any further issues. Cheers.
