### ISSUE TITLE
dimStability returns 0 for all dimension if they are labeled as characters instead of integers

### ISSUE THREAD

**Issue by winsonfzyang** [hfgolino/EGAnet#67]
Hello! I found another bug in `dimStability()`. It seems like it always returns 0 if the `orig.wc` argument is a character array rather than a numeric array. I could go about running the function twice, once with the character array, and one with the numeric array. However, is it possible to update the code make it run for two types of arrays?

**Comment by hfgolino** [comment]
Hi @winsonfzyang, Alex Christensen just fixed this bug. Thanks for your suggestion. In the future, please use the following template: EGAnet/.github/ISSUE_TEMPLATE/bug_report.md. Best wishes, Hudson.
