### ISSUE TITLE
TEFI (log(cor1) : NaNs produced)

### ISSUE THREAD

**Issue by pedro-ribeirosantiago** [hfgolino/EGAnet#72]
Dear Hudson Golino,

First of all, congratulations on your work, I'm a big fan of it. I was trying to use the function **tefi** from the EGAnet package. However, because my correlation matrix has some very small negative values (for example, the correlation between two items was -0.002), the **tefi** function is showing the warning message (**log(cor1) : NaNs produced**). I believe this happened because the function cannot take the log of a negative number. Is there any workaround regarding this problem?

Sorry, I cannot share the data but I can share the correlation matrix if needed.

Thanks in advance!

Kind Regards,
Pedro Santiago

**Comment by hfgolino** [comment]
Hi Pedro, thanks for your email!

I believe you're using an older version of the EGAnet package.

Two possible options now are: 1) re-install the package from CRAN; or 2)
use the absolute values of the correlation matrix. The newest version of
the package uses abs(cor) by default, to avoid this kind of error, ok? And
you're right, log of a negative number will return NaN.

Cheers,

Hudson



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* hfg9s@eservices.virginia.edu
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em sex., 7 de ago. de 2020 às 02:31, pedro-ribeirosantiago <
notifications@github.com> escreveu:

**Comment by pedro-ribeirosantiago** [comment]
Thanks Hudson! I realized I was not using the latest version. I installed the new version and the problem disappeared :)

Thanks again

Cheers,
Pedro
