### ISSUE TITLE
Changing labels and colours of dimStability plot

### ISSUE THREAD

**Issue by IreneBobevski** [hfgolino/EGAnet#74]
Hello,
I am new to R and network analysis. I have used EGA to estimate a network of psychological symptoms, and then used bootEGA and dimStability to estimate and plot the stability of the dimensions. I would like to change the item labels and the colour palette of the dimStability plot, preferably without having to re-run the estimations and the bootstrap. Is it possible to do this?   

Here is my code:

gboot_v2 <- bootEGA(gcombdata_v1, n=10000, model= "glasso", algorithm="louvain", 
			type = "resampling", plot.typicalStructure = TRUE, ncores=3)
gsc_v2 <- dimStability(gboot_v2, orig.wc = gega.v1$wc)

This is the code I used  to obtain the plot:
gsc_v2$items$plot.itemStability

I tried the code below to change the labels and colours, but it did not make a difference:
plot(gsc_v2$items$plot.itemStability, labels=colnames(gega_colnames_v1), palette="pastel")

**Comment by AlexChristensen** [comment]
Hello @IreneBobevski,

Thanks for reaching out on this -- a necessary feature we've neglected to demonstrate (we now provide examples in the documentation of our latest GitHub patch #75). The plotting method for the `itemStability`/`dimStability` functions uses ggplot2, so the plots can be changed using typical ggplot2 commands.

For the example you've provided, you should be able to change the plot with the following code:

```
# Change colors and labels (ignore warnings)
gsc_v2$items$plot.itemStability +
    ggplot2::scale_color_brewer(palette = "Pastel1", labels = colnames(gega_colnames_v1))
```

This should work without updating to our latest GitHub patch.

**Comment by IreneBobevski** [comment]
Hi Alex,

Many thanks for your very helpful reply. This did work and it changed the legend labels. But how could I changed the item labels (the labels of the ticks on the y-axis)?  I tried  +ggplot2::scale_y_discrete(labels=colnames(gega_colnames_v1)), but it did not do anything.

**Comment by AlexChristensen** [comment]
Aha, that is a bit tricky. The plot is rotated (which is not obvious), so the axes are reversed. You can use `+ ggplot2::scale_x_dicrete(labels = colnames(gega_colnames_v1))` and it should change the item labels.

**Comment by IreneBobevski** [comment]
Oh, now it makes sense. Thanks - changing the y to x worked.
