### ISSUE TITLE
UVA function

### ISSUE THREAD

**Issue by ciaranodriscoll** [hfgolino/EGAnet#78]
Hi,
Getting this error when trying to run the UVA function 

UVA.ra <- UVA(data = subnet, method = "wTO", type = "adapt", 
               reduce = TRUE, reduce.method = "latent", adhoc= TRUE)

Error in switch(corr, cor_auto = qgraph::cor_auto(data), pearson = cor(data,  : 
  EXPR must be a length 1 vector

if you try and input the correlation matrix instead you get this error:

Error in redundancy.process(data = data, cormat = cormat, n = n, model = model,  : 
  object 'cormat' not found

Also occurs when using the example from the package document so doesn't appear to be an issue with my data. 

# Select Five Factor Model personality items only
idx <- na.omit(m
               atch(gsub("-", "", unlist(psychTools::spi.keys[1:5])), colnames(psychTools::spi)))
items <- psychTools::spi[,idx]

# Change names in redundancy output to each item's description
key.ind <- match(colnames(items), as.character(psychTools::spi.dictionary$item_id))
key <- as.character(psychTools::spi.dictionary$item[key.ind])
if(interactive()){
  UVA(data = items, method = "wTO", type = "adapt",
      key = key, reduce.method = "latent")
}

**Comment by AlexChristensen** [comment]
Hi @ciaranodriscoll,

Could you try re-installing via GitHub (`devtools::install_github("hfgolino/EGAnet")`) and restart R/RStudio?

I don't get this error with the latest version. 

Thanks

**Comment by ciaranodriscoll** [comment]
Thanks this works.

BW
C

**Comment by ciaranodriscoll** [comment]
However if inputting the cor mat the error persists.

**Comment by AlexChristensen** [comment]
Ah, yes. Thanks for pointing this out.

A note on using a correlation matrix as input: Latent variable scores will not be able to be computed. Only the remove method would be able to be used.

In any case, I will need to change to code to adjust for correlation matrix input.

Cheers

**Comment by AlexChristensen** [comment]
I've created a new issue for the correlation matrix #79
