### ISSUE TITLE
Error running UVA

### ISSUE THREAD

**Issue by Richmull** [hfgolino/EGAnet#83]
Hi, Can you help with a possible issue please? I've run an EGA on a data frame 365x51 without a problem (code below: EGA). When I then try to run the UVA analysis, I get the following error:

Error in redund[[i]] : subscript out of bounds

I assume that as the EGA ran OK, there isn't an issue with the data file and, for the UVA, I've followed the coding example in Christensen, Garrido & Golino 10.31234/osf.io/4kra2. 
Thanks
Rich Mullen

EGA
data <- read_csv("Harry RST51.csv", col_names = TRUE, show_col_types = FALSE)
?read_csv
ega.RST51 <- EGA(data=data, algorithm="louvain", plot.EGA = FALSE)
plot(ega.RST51, plot.args = list(node.size = 8, edge.alpha = 0.2))

UVA
set.seed(6724)
data <- read_csv("Harry RST51.csv", col_names = TRUE, show_col_types = FALSE)
?read_csv
RST51red <- UVA (data, method = "wTO", type = "adapt", reduce=TRUE, reduce.method = "latent", adhoc=TRUE)
```

**Comment by AlexChristensen** [comment]
Hi @Richmull,

Thank you for pointing out this bug to us. The error comes from a recent change to `UVA`'s default arguments. Based on our latest revision of the manuscript, we know have `UVA` default to an automated process. This can be run using the following code on your data:

`RST51red <- UVA (data)`

`UVA` will handle the rest; however, if you are interested in following through with the manual procedure, then you can update the latest push to GitHub where I've corrected this error:

`devtools::install_github("hfgolino/EGAnet", build_vignettes = TRUE)`

Restart R/RStudio and you can re-run your previous code:

`RST51red <- UVA (data, method = "wTO", type = "adapt", reduce=TRUE, reduce.method = "latent", adhoc=TRUE)`

and it should work as defined in the current preprint. Just a heads up: We will be updating the preprint soon to match the automated procedure.

Let us know if any errors continue to occur.

Thank you!

**Comment by Richmull** [comment]
Hi Alex,
Thanks for the swift response. Short version works perfectly. Will try the manual version later.
Thanks again!

**Comment by Richmull** [comment]
...and the manual version works perfectly after updating. Thank you very much.

**Comment by AlexChristensen** [comment]
No problem!
