### ISSUE TITLE
dimensionStability error message

### ISSUE THREAD

**Issue by raphael-lorenzdelaigue** [hfgolino/EGAnet#86]
I get the following error message when computing dimensionStability on my bootega object:

``` {r}
bootstrap <- bootEGA(data,
                    iter = 1000, 
                    type = "resampling")

dimstab <- dimensionStability(bootstrap)
```

``` {r}
Item Stability Analysis

Organizing data...
An error has occurred in the 'homogenize.membership' function of 'itemStability':

Error in i_compare(comm1, comm2, method) : 
  At community.c:1092 : Cluster out of range, Invalid value

Please open a new issue on GitHub (bug report): https://github.com/hfgolino/EGAnet/issues/new/choose

Be sure to provide the following information:

To Reproduce:
 • Function error occurred in: homogenize.membership function of itemStability

R and EGAnet versions:
 • R version: 4.1.1
 • EGAnet version: 0.9.9

Operating System:
 • OS: Windows
 • Version: 10 x64 build 19042
Error in order(names(stability.dimensions)) : argument 1 is not a vector
```

My bootEGA command seems to work fine except for the two following warnings
``` {r}
1: In bootEGA(data, iter = 1000, type = "resampling") :
  Results are unique. Set the 'seed' argument for reproducible results (see examples)
2: In bootEGA(data, iter = 1000, type = "resampling") :
  Previous versions of EGAnet (<= 0.9.8) checked unidimensionality using uni.method = "expand" as the default
```

**Comment by raphael-lorenzdelaigue** [comment]
Setting the seed seemed to work.
First I got another error message after setting the seed

``` {r}
Item Stability Analysis

Organizing data...done

Computing results...
An error has occurred in the 'itemStability.plot' function of 'itemStability':

Error in loadNamespace(x) : there is no package called ‘ggpubr’

Please open a new issue on GitHub (bug report): https://github.com/hfgolino/EGAnet/issues/new/choose

Be sure to provide the following information:

To Reproduce:
 • Function error occurred in: itemStability.plot function of itemStability

R and EGAnet versions:
 • R version: 4.1.1
 • EGAnet version: 0.9.9

Operating System:
 • OS: Windows
 • Version: 10 x64 build 19042
Error in order(names(stability.dimensions)) : argument 1 is not a vector
```

But after installing ggpubr manually I was fine!

**Comment by AlexChristensen** [comment]
Thanks, @raphael-lorenzdelaigue!

Unfortunately, CRAN has limited the number of packages we can list as dependencies and therefore some packages need to be manually installed. We're working on a solution

**Comment by raphael-lorenzdelaigue** [comment]
Hi again @AlexChristensen.
Unfortunately I have had the error message again despite setting the seed.
I am performing the analysis on 5 different datasets:
Baseline - Full Sample, 
Baseline - Control Group, 
Baseline - Intervention Group, 
Follow-up - Control Group,
Follow-up - Intervention Group.

I get the error message on one of the 5 datasets, namely Baseline - Control Group.

I am sending you the data & additional info via e-mail.

**Comment by AlexChristensen** [comment]
Error was due to the Rand index not being able to be computed when the variables in a target or conversion dimension were all unique -- that is, the number of variables equaled the number of dimensions (e.g., 1, 2, 3)

Issue should be resolved
