### ISSUE TITLE
Bug in EGAnet::dimensionStability function

### ISSUE THREAD

**Issue by E-Mendez** [hfgolino/EGAnet#87]
Hi!
First of all, thanks for your work on grounding methodological decisions in the network psychometrics framework.

I tried to apply the methods proposed in "A psychometric network perspective on the validity and validation of personality trait questionnaires." (Christensen, Golino,  & Silvia, 2020), based on the supplementary script of the paper. 

The script works as expected with the database used in the paper, but it does not work with mine. 
The error I get is:

- `Error in order(names(stability.dimensions)) : argument 1 is not a vector`

I also get the following message: 

---
sc <- dimensionStability(boot)

Item Stability Analysis

Organizing data...
An error has occurred in the 'homogenize.membership' function of 'itemStability':

Error in i_compare(comm1, comm2, method) : 
  At community.c:1092 : Cluster out of range, Invalid value

Please open a new issue on GitHub (bug report): https://github.com/hfgolino/EGAnet/issues/new/choose

Be sure to provide the following information:

To Reproduce:
 • Function error occurred in: homogenize.membership function of itemStability

R and EGAnet versions:
 • R version: 4.1.1
 • EGAnet version: 0.9.9

Operating System:
 • OS: Linux
 • Version: 5.14.0-1-amd64 #1 SMP Debian 5.14.6-3 (2021-09-28)
Error in order(names(stability.dimensions)) : argument 1 is not a vector
---

I thought that maybe it was related to the fact that the EGAnet::EGA function finds 4 dimensions (louvain), while EGAnet::bootEGA, which used walktrap found 5. I specified the louvain algorithm in the second function and the problem persists, now I'm clueless. Perhaps has something to do with the structure of igraph's community data, but if it was that, it shouldn't work with the dataset proposed in the article. I'm clueless.

I provide a script and my data.

Cheers,

Eduardo from Chile

PS: this is my first bug report/contribution so maybe I didn't follow the reporting protocol. If something is missing please let me konw.

PS2: Couldn't add a .rmd file, sorry for this messy style, but below it is in text mode (copypaste to a new .rmd file). I can provide it through email or other means. 

---
title: "Bug in EGAnet::dimensionStability function"
author: "EMéndez"
date: "11/8/2021"
output: html_document
---

# Bug in EGAnet::dimensionStability function

This script is a modified version of the supplementary material in _Christensen, A. P., Golino, H., & Silvia, P. J. (2020). A psychometric network perspective on the validity and validation of personality trait questionnaires_. It actualizes the functions proposed, to its new names in the new versions of `EGAnet`

```{r}
# Load packages
library(psychTools)
library(EGAnet)
# Set seed for reproducibility
set.seed(6724)

# For help getting started, type browseVignettes("EGAnet")
#browseVignettes("EGAnet")


```
EGAnet (version 0.9.9) 
For help getting started, type browseVignettes("EGAnet")
 For bugs and errors, submit an issue to <https://github
[Database_Dryad2.xls](https://github.com/hfgolino/EGAnet/files/7500410/Database_Dryad2.xls)
.com/hfgolino/EGAnet/issues> 

NEW: EGAnet will write your Methods section for you. Type ?methods.section for more details 

MAJOR CHANGE: Unidimensionality adjustment in EGA functions has changed to the leading eigenvalue adjustment (see <https://doi.org/10.31234/osf.io/hz89e>)

https://github.com/hfgolino/EGAnet/blob/master/NEWS

Changes in version 0.9.8
- DEFUNCT: `node.redundant`, `node.redundant.names`, and `node.redundant.combine` will be defunct in next version. Please use `UVA`

```{r}
# Select Five Factor Model personality items only
idx <- na.omit(match(gsub("-", "", unlist(spi.keys[1:5])), colnames(spi)))
items <- spi[,idx]

spi.dictionary[which    
               (rownames(spi.dictionary) %in% colnames(items) )
               , ]$item
#idx #numero de columna

#items # base con sólo las columnas idx
#class(items) #data.frame



```

## My database= PCL-R

The two chucks below loads my data in which the error is present. If deleted, the script will run with no error with your data. If kept, it will show the error at  `EGAnet::dimensionStability` function.

### This chunk below loads the PCL-R data

Not that you will have to modify the directory of the spreadsheet to the one in your computer (attached in the bug report).

```{r}
library("readxl")
library(stringr)

base <- read_excel("/home/kroxa/Documents/bases_pcl-r/Database_Dryad2.xls", col_names = TRUE, sheet = 2 )
colnames(base)
base_flores <- base[, c(2:21)]

colnames(base_flores)

#key_flores <- 
key_flores <- paste0(colnames(base_flores), ": " , fraseos)
key_flores


 
colnames(base_flores) <- str_replace(colnames(base_flores), "PCL-R ", "V")
```

### This chunk below checks if my data and the one in the paper have the same format and transforms it to match if it does not.

```{r}
aa <- as.data.frame(base_flores)
class(aa) == class(items)
items <- aa
class(key)== class(key_flores)
key <- key_flores
```

```{r}
# Change names in redundancy output to each item's description
#key.ind <- match(colnames(items), as.character(spi.dictionary$item_id))
#key <- as.character(spi.dictionary$item[key.ind])

redund <- UVA(items, method = "wTO", type = "adapt", reduce = FALSE, auto = FALSE, key = key)
# Warning: Automated UVA is not recommended for types other than 'reduce.method = "threshold"'

```

### This table matched the one in your example

```{r}
kableExtra::kable(
  redund$redundancy$redundant[1])
```
__CHECK!__

The name of this item list, 'Am full of ideas.', is the item that is redundant with
the items listed below it. The $redundant list is structured this way for each item that is
redundant with other items. This structure, however, is verbose and difficult to manage. In
order to navigate the process of merging items, the function node.redundant.combine
should be used.

## Combining redundant responses

```{r}
combined.nr <- UVA(items, method = "wTO", type = "adapt", auto = FALSE, key = key, reduce.method = "latent")
```

When entering this code, the R console will output each item list with a selection of
possible redundant nodes (see Figure SI1) and an associated “redundancy chain” plot will
appear (see Figure SI2). When examining the possible redundant nodes, the reader may
notice that there were four items identified previously—that is, 'Am able to come up with
new and different ideas.', 'Am an original thinker.', 'Love to think up new
ways of doing things.', and 'Have a vivid imagination.' (Table SI1).

__Said menu is obtained with reduce = TRUE__

```{r}
#combined.nr <- UVA(items, method = "wTO", type = "adapt", auto = FALSE, key = key, reduce.method = "latent")

combined.nr2 <- UVA(items, method = "wTO", type = "adapt", auto = FALSE, key = key, reduce = TRUE)
#reduce.method = Character. How should data be reduced? Defaults to "latent"

#both are doing t
```

```{r}
names(combined.nr2)
combined.nr2$reduced$merged
combined.nr2$reduced$data
combined.nr2$redundancy


```

```{r}
# Este lo modifiqué

# New items
new.items <- combined.nr2$reduced$data
new.items
# Examine dimensions
ega <- EGA(combined.nr2$reduced$data, model = "glasso", algorithm = "louvain", plot.type = "qgraph", plot.args = list())

#plot.type = c("GGally", "qgraph"),
#  plot.args = list(),
```
 
EGA has been recently adapted to include the Louvain community detection algorithm
(Blondel, Guillaume, Lambiotte, & Lefebvre, 2008), which has demonstrated comparable or
better performance than the Walktrap algorithm (Pons & Latapy, 2006) in identifying
dimensions (Christensen, 2020). For this reason, we estimated the dimensions of the network
using the Louvain algorithm. Based on Figure SI4, there are five dimensions identified for
these components. To view the composition of these dimensions, the following code should
be entered:

## Table SI2

```{r}
kableExtra::kable(ega$dim.variables)
ega$dim.variables
```

# Compute standardized node strength

```{r}
# Compute standardized node strength

net.loads(ega)$std
kableExtra::kable(net.loads(ega)$std)

```

The net.loads function computes each node’s standardized node strength for each
dimension in the network. Therefore, Table SI3 can be interpreted similarly as an
exploratory factor analysis loading matrix. When examining the network loadings matrix,
there were a couple things worth noting. First, the network loadings are much smaller than
the loadings of a traditional factor loading matrix. The largest loading is 0.409 for the
original ideation component in the openness to experience dimension. By traditional factor
analysis standards, this is a weak factor loading. This difference in the magnitude of the
loadings is due to the association measure underlying the computation of the loading—that
is, partial vs. zero-order correlations. The network loadings thus represent partial correlation
loadings, meaning that 0.409 is actually a very large loading.

__(Important 	$\uparrow$ )__

## Structural consistency. 

In the manuscript, we proposed structural consistency as
a complementary measure to internal consistency. To compute structural consistency, we
must first apply the bootEGA function, which will compute the bootstrap analysis. Once this
procedure is completed, the dimStability function can be applied.

Error in dimStability(boot, orig.wc = ega$wc) : 
  could not find function "dimStability"

```{r}
# Set seed
set.seed(6724)
# Compute bootstrap
boot <- bootEGA(new.items
                , model = "glasso",
type = "parametric", 
plot.typicalStructure = FALSE, 
iter = 250,
algorithm ="louvain") # 250 = 1 min en original dataset
# Compute structural consistency

boot
?bootEGA
```

Warning in bootEGA(new.items, n = 500, model = "glasso", type = "parametric",  :
  Previous versions of EGAnet (<= 0.9.8) checked unidimensionality using uni.method = "expand" as the default

# Error in order(names(stability.dimensions)) : argument 1 is not a vector

__This chunk below is the problematic one $\downarrow$

```{r}
sc <- dimensionStability(boot, orig.wc = ega$wc)
sc <- dimensionStability(boot)
# Print structural consistency
sc$dimensions
sc$dimension.stability


```

Table SI4
Structural consistency values for each dimension

```{r}
(sc$dimension.stability$structural.consistency)


```

```{r}
# Item stability statistics plot
sc$item.stability$plot

```

The item stability plot reveals that most components within the agreeableness
dimension are consistently being identified within their original dimension. To view how
these components are positioned across dimensions, the items$item.dim.rep object can be
viewed:

```{r}
# View item stability across dimensions
#View(sc$items$item.dim.rep)
sc$item.stability$membership$bootstrap

data.frame(sc$item.stability$mean.loadings)
data.frame(sc$item.stability$item.stability$all.dimensions)

data.frame(sc$item.stability$item.stability$empirical.dimensions)


sc$dimension.stability

```

## Extra: Input is a square matrix. Changing 'reduce.method' to "remove"

Not related, but I tried to apply UVA to a correlation matrix and couldn't create latent variables out of redundant items. Is this a "meanwhile" thing, or is it there a substantial impediment to apply the methodology to correlation matrices instead of raw data (i.e. boostrap)??

**Comment by AlexChristensen** [comment]
Hi @E-Mendez,

Regarding the `dimensionStability` and `itemStabliity`, we only just recently fixed this bug. It should be fixed in the latest GitHub package: `devtools::install_github("hfgolino/EGAnet")`

Regarding the correlation matrix in UVA, latent variables cannot be created because you need the raw data to estimate scores for each person. The correlation matrix does not contain each data point for each person. Therefore, latent variables can only be used when there is raw data.

As a heads up, we'll be removing and eventually updating the vignettes as some of the information is now out of date with current updates in *EGAnet*.

Let us know if the item/dimension stability issue is resolved.

Thank you,
Alex

**Comment by E-Mendez** [comment]
Hi Alex,

Thanks for your quick reply. The bug is effectively fixed on the github version of the package. =)

Regarding the unrelated topic of bootstrapping from a correlation matrix, I think I have run processes that create an artifical incidence matrix using the correlation matrix and the sample size as imputs. I'm not an expert on the field (just transitioning from "discursive" social sciences to empirical data analysis). I recall it was "parametric boostrap".

Anyways, thanks for your contributions, I really admire your work.

Cheers!

**Comment by hfgolino** [comment]
Hi Mendez, thanks for your nice message.

The EGAnet package version 1.0.0 is also now available on CRAN!

Cheers,

Hudson



*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* ***@***.***
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em qua., 10 de nov. de 2021 às 11:01, E-Mendez ***@***.***>
escreveu:

**Comment by E-Mendez** [comment]
Awesome!

Thanks for your quick reply, and your contributions to the field!

Eduardo
