### ISSUE TITLE
Error with external (?) community detection algorithm

### ISSUE THREAD

**Issue by raphael-lorenzdelaigue** [hfgolino/EGAnet#88]
Hi,
I am running bootEGA on a dataset because I am interested in the community structure of the "typical network" underlying my data.

``` {r}
bootEGA(baseline_kg,
              iter = 1000, 
              type = "resampling",
              seed = 42,
              ncores = 1)
```

(I am using only one core because I was having R crashes with multiple cores).

However, I am getting the following error message

``` {r}
Error in igraph::cluster_leading_eigen(NetworkToolbox::convert2igraph(abs(cor.data))) : 
  At arpack.c:1001 : ARPACK error, Maximum number of iterations reached
```

Googling the error, I stumbled upon this issue:
https://github.com/igraph/igraph/issues/512

The following solutions are being proposed: 
(https://github.com/igraph/igraph/issues/512#issuecomment-63691590)

" - Remove isolated vertices from your graph
  - Decompose your graph into connected components and calculate eigenvectors for the individual components only. (This is because if you have two connected components, then each connected component has eigenvectors on their own and any linear combination of these eigenvectors is also a valid eigenvector).
   - Increase the maximum number of iterations ARPACK is allowed to take on your graph as a last resort."

For the first two solutions, I would need to access the graph but I am not sure if that is possible because I don't know if the code breaks before the "typical" network is being generated. (How can I "catch" the graph?). Also, I am only a psychology student and I didn't have linear algebra so I don't know much about calculating eigenvactors.

For the third solution, I don't know how to set the number of iterations for ARPACK. I do not know how EGAnet and ARPACK interact.

Could maybe someone assist me with this?

I can send the data via e-mail so that you can try and reproduce the error.

Best,

Raphael Lorenz-de Laigue

**Comment by hfgolino** [comment]
Hi,

Thanks for your contact.

Update EGAnet from GitHub and see if the problem persists.

Thanks

**Comment by AlexChristensen** [comment]
Adding to what @hfgolino said:

Patched a few days ago on GitHub: https://github.com/hfgolino/EGAnet/commit/28c64cc0aa4c13fd6db9a0dcf4e508ad9e576c5a

The patch first tries `igraph::cluster_leading_eigen`. If an error is thrown, then `igraph::cluster_louvain` is used.

A warning is thrown to notify that the Louvain algorithm was used instead.

The Louvain algorithm performs comparable to the Leading Eigenvalue algorithm for unidimensional structures (see [here](https://psyarxiv.com/hz89e/) for simulation evidence).

**Comment by raphael-lorenzdelaigue** [comment]
Hi, thanks for the quick answer.
With the updated version, bootEGA runs fine.
However, now I get a "R Session Aborted R encountered a fatal error. The session was terminated" when trying to run dimensionStability on the bootEGA object.
(Which is the next step in my analysis).
I also do not get any warning about the Louvain algorithm

**Comment by AlexChristensen** [comment]
If the error happens in the bootstrap, then it might not get mentioned. For bootstrapping, Louvain would only be used a few times at most, so it's safe assume Leading Eigenvalue is being used most of the time.

Could you send me your bootEGA object so I can look into the `dimensionStability` issue?

alexpaulchristensen@gmail.com

**Comment by AlexChristensen** [comment]
Bug has been fixed: https://github.com/hfgolino/EGAnet/commit/91ef261fd381451cbf986dc676cd1d02f3aff63e

`NA` communities in the empirical EGA was freezing in `igraph::compare()`
