### ISSUE TITLE
Function error occurred in: homogenize.membership function of itemStability

### ISSUE THREAD

**Issue by raphael-lorenzdelaigue** [hfgolino/EGAnet#91]
I just got the following error message when performing itemStability analysis on a bootEGA object (can send it via e-mail if it helps)

``` {r}
Error in if (all(target.wc == new.vec)) { : 
  missing value where TRUE/FALSE needed
```

R and EGAnet versions:
 • R version: 4.1.2
 • EGAnet version: 1.0.1

Operating System:
 • OS: Windows
 • Version: 10 x64 build 19044
 
 Best,
 
 Raphael Lorenz-de Laigue

**Comment by AlexChristensen** [comment]
Hi @raphael-lorenzdelaigue,

Could you send the R environment to me: alexpaulchristensen@gmail.com

**Comment by raphael-lorenzdelaigue** [comment]
Done! :)

**Comment by AlexChristensen** [comment]
Assuming bug is fixed in https://github.com/hfgolino/EGAnet/issues/91
