### ISSUE TITLE
bootEGA plot.type = "qgraph" not working

### ISSUE THREAD

**Issue by norinski** [hfgolino/EGAnet#93]
Hi,

I have successfully run bootEGA function; however, it automatically shows the plot in "GGally" format. I tried changing it to "qgraph" as follows:

`bootdata <- bootEGA(
  data,
  iter= 1000, 
  type = "resampling",
  model = "glasso",
  corr="spearman",
  seed=1234,
  plot.type = "qgraph")`

but it keeps on showing the display of GGally. I'm not sure if I am doing something wrong? Thanks!

**Comment by norinski** [comment]
> plot(boot.wmt, plot.type = "qgraph")

Thanks! It worked :).

**Comment by hfgolino** [comment]
Alex, plot.type = qgraph is indeed not working.

I wonder if we should keep the qgraph plotting system at all. What do you
think?


*Hudson Golino*
*Assistant Professor*
*Department of Psychology*

*E* ***@***.***
*P* 434.806.1915

*University of Virginia*
1023 Millmont St, Office 115
Charlottesville, VA 22903




Em ter., 7 de jun. de 2022 às 17:30, Alexander Christensen <
***@***.***> escreveu:
