### ISSUE TITLE
Changing legend title

### ISSUE THREAD

**Issue by raphael-lorenzdelaigue** [hfgolino/EGAnet#95]
Hi,

given a bootEGA object, how to quickly change the legend title?
This command doesn't do it for me:
plot(my_bootega, plot.args = list(color.legend = "Legend title"))

[my_bootega.zip](https://github.com/hfgolino/EGAnet/files/8940485/my_bootega.zip)

Best,

R.

**Comment by AlexChristensen** [comment]
closing with fix
