### ISSUE TITLE
EGA Error during Unidimensionality Check

### ISSUE THREAD

**Issue by cjschmank** [hfgolino/EGAnet#98]
Receiving the following error when attempting to run dataset through EGA function:

Error in igraph::cluster_louvain(igraph_network, resolution = resolution) : 
  unused argument (resolution = resolution)

RStudio wanted me to be sure to include the following information associated with the error as well:

To Reproduce:
 • Function error occurred in: unidimensionality.check function of EGA

R and EGAnet versions:
 • R version: 3.6.1
 • EGAnet version: 1.2.0

Operating System:
 • OS: Darwin
 • Version: 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64

If you need any additional information please let me know!

**Comment by hfgolino** [comment]
Hi!

Please install the new version of the package from GitHub, the issue was
solved on version 1.2.3.

**Comment by cjschmank** [comment]
Thank you for your quick response previously!  I updated the package, however, I am still receiving the same error message as before.

An error has occurred in the 'unidimensionality.check' function of 'EGA':

Error in igraph::cluster_louvain(igraph_network, resolution = resolution) : 
  unused argument (resolution = resolution)

To Reproduce:
 • Function error occurred in: unidimensionality.check function of EGA

R and EGAnet versions:
 • R version: 3.6.1
 • EGAnet version: 1.2.3

Operating System:
 • OS: Darwin
 • Version: 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64

**Comment by AlexChristensen** [comment]
@cjschmank, 

This issue is actually associated with {igraph}. If you update to {igraph}'s latest version, then the issue should be resolved.

{igraph} versions 1.2.7 and earlier did not have the `resolution` parameter for the `cluster_louvain` function.

**Comment by AlexChristensen** [comment]
Closing... requiring {igraph} version >= 1.3.0 in DESCRIPTION file for future installs
